######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 4 22:53:29 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += webmain.cpp

QT += network
QT += webkit
